/* eslint-disable quotes */
/* eslint-disable quote-props */

const data = [
  {
    Title: "Scary Movie",
    Year: "2000",
    imdbID: "tt0175142",
    Type: "movie",
    Poster: "https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    'imdbRating': '6',
    Country: "USA",
    Genre: "Comedy, horror",
    Director: "Keenen Ivory Wayans",
    Runtime: "88 min",
  },
  {
    Title: "Scary Movie 2",
    Year: "2001",
    imdbID: "tt0257106",
    Type: "movie",
    Poster: "https://m.media-amazon.com/images/M/MV5BMzQxYjU1OTUtYjRiOC00NDg2LWI4MWUtZGU5YzdkYTcwNTBlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    'imdbRating': '5',
    Country: "USA",
    Genre: "Comedy, horror",
    Director: "Keenen Ivory Wayans",
    Runtime: "83 min",
  },
  {
    Title: "Scary Movie 3",
    Year: "2003",
    imdbID: "tt0306047",
    Type: "movie",
    Poster: "https://m.media-amazon.com/images/M/MV5BNDE2NTIyMjg2OF5BMl5BanBnXkFtZTYwNDEyMTg3._V1_SX300.jpg",
    'imdbRating': '5',
    Country: "USA",
    Genre: "Comedy, horror",
    Director: "David Zucker",
    Runtime: "83 min",
  },
  {
    Title: "Scary Movie 4",
    Year: "2006",
    imdbID: "tt0362120",
    Type: "movie",
    Poster: "https://m.media-amazon.com/images/M/MV5BZmFkMzc2NTctN2U1Ni00MzE5LWJmMzMtYWQ4NjQyY2MzYmM1XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    'imdbRating': '5',
    Country: "USA",
    Genre: "Comedy, horror",
    Director: "David Zucker",
    LengRuntimeth: "85 min",
  },
  {
    Title: "Scary Movie 5",
    Year: "2013",
    imdbID: "tt0795461",
    Type: "movie",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTc5OTIxMjQ4NF5BMl5BanBnXkFtZTcwOTAyNDcyOQ@@._V1_SX300.jpg",
    'imdbRating': '3',
    Country: "USA",
    Genre: "Comedy, horror",
    Director: "David Zucker",
    Runtime: "86 min",
  },
];

export default data;
