/* eslint-disable quotes */
/* eslint-disable quote-props */
const data = [
  {
    'Title': 'Scary Movie',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '1',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Pirates of the Caribbean: The Curse of the Black Pearl',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '9.9',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 3',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '6.1',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Don\'t Be a Menace to South Central While Drinking Your Juice in the Hood',
    'Year': '1996',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '10',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Guardians of the Galaxy Vol. 2',
    'Year': '200',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '9',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 6',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '5',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 6',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '2.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 6',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '1.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 6',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '6.8',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 6',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '8.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 6',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '5.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
];

export default data;
