/* eslint-disable quotes */
/* eslint-disable quote-props */
const data = [
  {
    'Title': 'Scary Movie',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '6.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Pirates of the Caribbean: The Curse of the Black Pearl',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '6.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 3',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '6.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Don\'t Be a Menace to South Central While Drinking Your Juice in the Hood',
    'Year': '1996',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '6.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 5',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '6.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    'Title': 'Scary Movie 6',
    'Year': '2000',
    'Rated': 'R',
    'Released': '07 Jul 2000',
    'Runtime': '88 min',
    'Genre': 'Comedy',
    'Director': 'Keenen Ivory Wayans',
    'Writer': 'Shawn Wayans, Marlon Wayans, Buddy Johnson, Phil Beauman, Jason Friedberg, Aaron Seltzer',
    'Actors': 'Carmen Electra, Dave Sheridan, Frank B. Moore, Giacomo Baessato',
    'Plot': 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.',
    'Language': 'English',
    'Country': 'USA',
    'Awards': '7 wins & 6 nominations.',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMGEzZjdjMGQtZmYzZC00N2I4LThiY2QtNWY5ZmQ3M2ExZmM4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    'Ratings': [
      {
        'Source': 'Internet Movie Database',
        'Value': '6.2/10',
      },
      {
        'Source': 'Rotten Tomatoes',
        'Value': '53%',
      },
      {
        'Source': 'Metacritic',
        'Value': '48/100',
      },
    ],
    'Metascore': '48',
    'imdbRating': '6.2',
    'imdbVotes': '223,312',
    'imdbID': 'tt0175142',
    'Type': 'movie',
    'DVD': '12 Dec 2000',
    'BoxOffice': 'N/A',
    'Production': 'Dimension Films',
    'Website': 'N/A',
    'Response': 'True',
  },
  {
    "Title": "Guardians of the Galaxy Vol. 2", "Year": "2017", "Rated": "PG-13", "Released": "05 May 2017", "Runtime": "136 min", "Genre": "Action, Adventure, Comedy, Sci-Fi", "Director": "James Gunn", "Writer": "James Gunn, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Jim Starlin (Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Steve Gerber (Howard the Duck created by), Val Mayerik (Howard the Duck created by)", "Actors": "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel", "Plot": "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father the ambitious celestial being Ego.", "Language": "English", "Country": "USA", "Awards": "Nominated for 1 Oscar. Another 14 wins & 52 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.6/10" }, { "Source": "Rotten Tomatoes", "Value": "85%" }, { "Source": "Metacritic", "Value": "67/100" }], "Metascore": "67", "imdbRating": "7.6", "imdbVotes": "531,435", "imdbID": "tt3896198", "Type": "movie", "DVD": "N/A", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True",
  },

];

export default data;
